
package tour.clips;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClipsServer", targetNamespace = "http://clips.tour/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClipsServer {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clipsEngine", targetNamespace = "http://clips.tour/", className = "tour.clips.ClipsEngine")
    @ResponseWrapper(localName = "clipsEngineResponse", targetNamespace = "http://clips.tour/", className = "tour.clips.ClipsEngineResponse")
    @Action(input = "http://clips.tour/ClipsServer/clipsEngineRequest", output = "http://clips.tour/ClipsServer/clipsEngineResponse")
    public List<String> clipsEngine(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
