
package tour.clips;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClipsServerImplService", targetNamespace = "http://clips.tour/", wsdlLocation = "http://localhost:8081/WS/ClipsServer?wsdl")
public class ClipsServerImplService
    extends Service
{

    private final static URL CLIPSSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIPSSERVERIMPLSERVICE_EXCEPTION;
    private final static QName CLIPSSERVERIMPLSERVICE_QNAME = new QName("http://clips.tour/", "ClipsServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WS/ClipsServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIPSSERVERIMPLSERVICE_WSDL_LOCATION = url;
        CLIPSSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public ClipsServerImplService() {
        super(__getWsdlLocation(), CLIPSSERVERIMPLSERVICE_QNAME);
    }

    public ClipsServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIPSSERVERIMPLSERVICE_QNAME, features);
    }

    public ClipsServerImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIPSSERVERIMPLSERVICE_QNAME);
    }

    public ClipsServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIPSSERVERIMPLSERVICE_QNAME, features);
    }

    public ClipsServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClipsServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClipsServer
     */
    @WebEndpoint(name = "ClipsServerImplPort")
    public ClipsServer getClipsServerImplPort() {
        return super.getPort(new QName("http://clips.tour/", "ClipsServerImplPort"), ClipsServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClipsServer
     */
    @WebEndpoint(name = "ClipsServerImplPort")
    public ClipsServer getClipsServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://clips.tour/", "ClipsServerImplPort"), ClipsServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIPSSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw CLIPSSERVERIMPLSERVICE_EXCEPTION;
        }
        return CLIPSSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
